Feature/phone number parsing
boekuwzending/php-sdk pull request #23
Opened 2021-09-23 14:12 UTC by CodeCasterNL

2021-09-23 14:13 UTC, CodeCasterNL commented
Dit wordt v1.0.0.

2021-09-23 14:27 UTC, rvmourik requested changes
In composer.json moet dan ook het versienummer worden aangepast.

2021-09-24 11:01 UTC, CodeCasterNL commented
@rvmourik die staat bij dit project niet in composer.json, wordt door Packagist afgeleid uit de tag AFAIK?

2021-09-24 11:01 UTC, rvmourik commented
> @rvmourik die staat bij dit project niet in composer.json, wordt door Packagist afgeleid uit de tag AFAIK?

zie het ja, nevermind dan.

2021-09-24 11:02 UTC, rvmourik approved these changes

2021-09-24 12:43 UTC, merged