Added matrix support
boekuwzending/php-sdk pull request #8
Opened 2020-07-22 13:50 UTC by jvergers

2020-07-27 07:11 UTC, rvmourik approved these changes

2020-07-28 14:56 UTC, mwansinck requested changes

2020-07-28 14:56 UTC, mwansinck commented on src/Resource/Matrix.php
> +     * @var array|MatrixRate
```suggestion
     * @var MatrixRate[]
```

2020-07-28 14:56 UTC, mwansinck commented on src/Resource/Matrix.php
> +     * @param array|MatrixRate $rates
```suggestion
     * @param MatrixRate[] $rates
```

2020-07-28 14:56 UTC, mwansinck commented on src/Resource/Matrix.php
> +     * @return array|MatrixRate
```suggestion
     * @return MatrixRate[]
```

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/MatrixRateSerializer.php
> +        $matrixRate->setService($serializer->deserialize($data['service'], Service::class));
```suggestion
        $matrixRate->setPrice($data['price']);
        $matrixRate->setService($serializer->deserialize($data['service'], Service::class));
```

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/MatrixRateSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/DimensionsSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/MatrixRateSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/MatrixSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/MatrixSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/ServiceSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/ServiceSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-07-28 14:56 UTC, mwansinck commented on src/Serializer/DimensionsSerializer.php
> +     * @inheritDoc
Inherit doc even vervangen door volwaardig docblock

2020-08-11 07:13 UTC, jvergers commented
Wordt met Track and trace meegenomen

2020-08-11 07:13 UTC, closed without merging